# Generated by Django 5.1.3 on 2024-11-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participation',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('members', 'Members Only'), ('ateneans', 'Ateneans Only')], default='everyone', max_length=10),
        ),
    ]
