# Generated by Django 5.1.3 on 2024-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('COA', 'COA'), ('LIONS', 'LIONS'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
    ]
