# Generated by Django 5.1.3 on 2024-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(default='DEFAULT_CODE', max_length=10, unique=True),
        ),
    ]
