# Generated by Django 5.1.3 on 2024-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(choices=[('event_type', 'Event Type'), ('event_theme', 'Event Theme')], default='', max_length=50),
        ),
    ]
