# Generated by Django 5.1.3 on 2024-11-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_category',
        ),
    ]
